README.md

Follow-up change of https://github.com/confio/tgrade/pull/210

Fix License paragraph in README

---

testing/poe_test.go
x/poe/client/cli/query.go
x/poe/keeper/grpc_query.go

Fix validators query

---

x/poe/client/cli/tx.go
x/poe/contract/tgrade_valset.go
x/poe/contract/tgrade_valset_integration_test.go

Adds: `$ tgrade tx poe unjail --from mykey`
+ contract integration test case

Add Unjail command

---

Makefile
x/poe/client/cli/query.go
x/poe/contract/contractio.go
x/poe/contract/tg4.go
x/poe/contract/tgrade_validator_voting_integration_test.go
x/poe/contract/tgrade_valset.go
x/poe/contract/tgrade_valset_integration_test.go
x/poe/keeper/contracts.go
x/poe/keeper/grpc_query.go
x/poe/keeper/grpc_query_test.go
x/poe/keeper/poetesting/mock_contracts.go
x/poe/module_test.go
x/poe/types/poe.go
x/poe/wasm/query_plugin.go
x/poe/wasm/query_plugin_test.go

Resolves #226  
- Server side: page key in result set
- CLI: page key encoding

Set pagination result value

---

testing/fraud_test.go
testing/main_test.go
testing/poe_test.go
testing/system.go
x/twasm/abci.go
x/twasm/abci_test.go
x/twasm/contract/callback_msgs.go

Resolves #187 
Resolves #232 
Classic multi project integration error 🤦

Handle double signing

---

x/poe/contract/tg4_engagement.go
x/poe/contract/tg4_engagement_integration_test.go
x/poe/keeper/contracts.go
x/poe/keeper/grpc_query.go
x/poe/keeper/legacy_distribution_querier.go
x/poe/keeper/legacy_distribution_querier_test.go
x/poe/keeper/poetesting/mock_contracts.go

Delegated withdraw address

---

.circleci/config.yml
Dockerfile
go.mod

Resolves: #207
https://circleci.com/developer/images/image/cimg/go
https://hub.docker.com/layers/golang/library/golang/1.17/images/sha256-0e633e6b67296a31dccdab5b33478cc54e088ddb70f755774e456e7a66867444?context=explore

Update Go version to v1.17

---

.github/dependabot.yml

Scan for Go module and github action upgrades

Initial dependabot config

---

go.mod
go.sum

SDK patch version upgrade only

Bump cosmos-sdk version to v0.45.1

---

x/poe/contract/contractio.go
x/poe/contract/contractio_integration_test.go
x/poe/contract/tg4_stake_integration_test.go
x/poe/keeper/msg_server.go
x/poe/keeper/msg_server_test.go

Return completion time on unbond

---

.github/workflows/codeql-analizer.yml

Resolves #173 
Add CodeQL Action for checking common bugs:
- security and code quality issues
- custom queries for Cosmos SDK based projects (https://github.com/crypto-com/cosmos-sdk-codeql)

Add static checking for common bug patterns

---

testing/cli_test.go
x/poe/types/genesis.go
x/poe/types/genesis_test.go
x/twasm/module.go
x/twasm/types/genesis.go
x/twasm/types/genesis_test.go
x/twasm/types/wasm_genesis_helper.go

Resolves #61 
-[X] duplicate pubkeys in gentx (poe)
-[X] duplicate pinned contracts (twasm)
-[X] code_ids not existing for pinned contract (twasm)
-[X] contract address not existing for privileged contracts (twasm)

Genesis Validation

---

.circleci/config.yml

Resolves #278 
Enable code coverage upload (as in wasmd)
I have "activated" this repo in https://app.codecov.io/gh/confio/tgrade/settings

Enable code coverage upload

---

contrib/local/setup_tgrade.sh

Added some fixes to the script.
Update script to work with both linux and OSX (`date`command fix).

Fix script

---

cmd/tgrade/testnet.go
testing/cli.go

Resolves #316 
Simply stored with node0 seeds

Store testnet seeds

---

x/poe/bootstrap.go
x/poe/client/cli/query.go
x/poe/keeper/keeper.go
x/poe/types/poe.go
x/twasm/contract/incoming_msgs.go
x/twasm/types/privilege.go

Apply code quality fixes and doc

---

x/poe/keeper/genesis.go

Make it easier to find the failing gentx

Add better output for gentx failure

---

go.mod
go.sum

Bump wasmd to v0.25.0

---

Dockerfile
Makefile
go.mod
go.sum

Upgrade to v1.0.0-beta10
Add static compilation as in wasmd

Upgrade wasmvm version

---

contrib/local/setup_tgrade.sh

Add a member so that genesis validation succeeds

Seed local setup script with AP member

---

x/poe/keeper/keeper.go

Add cache for PoE contract addresses

---

Dockerfile
go.mod
go.sum
testing/cli.go
testing/fraud_test.go
third_party/proto/cosmwasm/wasm/v1/proposal.proto
third_party/proto/cosmwasm/wasm/v1/query.proto
third_party/proto/cosmwasm/wasm/v1/types.proto
x/twasm/testing/contract_keeper_mock.go

Upgrades [wasmd](https://github.com/CosmWasm/wasmd/releases/tag/v0.27.0) including wasmvm

Upgrade to wasmd v0.27.0

---

app/app.go

Remove evidence module for PoE

---

go.mod
go.sum
x/twasm/keeper/test_common.go

Bump ibc-go version to v3.0.1

---

x/poe/bootstrap.go
x/poe/simulation/genesis.go

No funds required for gov voting init on bootstrap

---

app/app.go
x/poe/bootstrap.go
x/poe/keeper/keeper.go

Init poe contract cache on restart

---

scripts/statesync.sh

Add statesync example script

---

cmd/tgrade/root.go
testing/fee_test.go

Add max fees limit to prevent too high fees

---

x/poe/client/cli/flags.go
x/poe/client/cli/query.go
x/poe/client/cli/tx.go

This fixes the main build in CI

Remove duplicate flags

---

x/poe/client/cli/tx.go
x/poe/contract/tg4_engagement.go

Add set-withdraw-address cli command

---

x/poe/abci.go
x/poe/keeper/keeper.go
x/poe/module.go
x/poe/wasm/query_plugin.go
x/poe/wasm/query_plugin_test.go

Add validator votes query for valset contract

---

v2.0.1-priv_checksums.txt

Add v2.0.1 checksums

---

SECURITY.md

Add discord addresses
